# Generated by Django 6.0.1 on 2026-01-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyorder",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("submitted", "Submitted")],
                default="draft",
                max_length=20,
            ),
        ),
    ]
