# Generated by Django 6.0.1 on 2026-02-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_globalsettings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="globalsettings",
            name="deadline_time",
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="deadline_breakfast",
            field=models.TimeField(
                default="10:00", help_text="Deadline for breakfast orders"
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="deadline_lunch",
            field=models.TimeField(
                default="10:00", help_text="Deadline for lunch orders"
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="deadline_olovrant",
            field=models.TimeField(
                default="10:00", help_text="Deadline for olovrant orders"
            ),
        ),
        migrations.AlterField(
            model_name="dailyorder",
            name="status",
            field=models.CharField(default="submitted", max_length=20),
        ),
    ]
