# Generated by Django 5.1.15 on 2026-02-22 15:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_passwordresettoken"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="passwordresettoken",
            index=models.Index(
                fields=["user", "used", "expires_at"],
                name="api_passwor_user_id_fac10a_idx",
            ),
        ),
    ]
