# Generated by Django 5.1.15 on 2026-02-26 14:24

from django.db import migrations, models

import api.models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_clientsettings_visible_meals_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalsettings",
            name="report_email_recipients",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of email addresses that receive the daily order report.",
            ),
        ),
        migrations.AlterField(
            model_name="clientsettings",
            name="visible_meals",
            field=models.JSONField(blank=True, default=api.models._default_all_meals),
        ),
    ]
