# Generated by Django 5.1.15 on 2026-03-05 13:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_emailverificationtoken_userprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="dailyorder",
            index=models.Index(
                fields=["date", "status"], name="api_dailyor_date_d42ee6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailyorder",
            index=models.Index(
                fields=["is_auto"], name="api_dailyor_is_auto_f68526_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailyorder",
            index=models.Index(
                fields=["created_at"], name="api_dailyor_created_c1e8b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["registration_status", "registration_date"],
                name="pending_reg_idx",
            ),
        ),
    ]
