# Generated by Django 5.1.15 on 2026-03-05 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_add_query_performance_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="dailyorder",
            name="api_dailyor_date_d42ee6_idx",
        ),
    ]
