# Generated by Django 5.1.15 on 2026-03-13 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_add_query_performance_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PortionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "coefficient",
                    models.DecimalField(
                        decimal_places=4,
                        help_text=(
                            "Multiplier applied to template "
                            "base_weight_grams. 1.0 = 100%."
                        ),
                        max_digits=5,
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="DailyMealPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, unique=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meal_plans_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="MealTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("breakfast", "Raňajky"),
                            ("lunch", "Obed"),
                            ("snack", "Olovrant"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("weight_label", models.CharField(blank=True, max_length=100)),
                (
                    "base_weight_grams",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "menu_variant",
                    models.CharField(
                        blank=True,
                        help_text=(
                            "Leave empty for breakfast/snack. " "E.g. 'A', 'B', 'C'."
                        ),
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["category", "menu_variant", "name"],
                "indexes": [
                    models.Index(
                        fields=["category", "is_active"],
                        name="api_mealtem_categor_f5af8e_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MealPlanItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("breakfast", "Raňajky"),
                            ("lunch", "Obed"),
                            ("snack", "Olovrant"),
                        ],
                        max_length=20,
                    ),
                ),
                ("menu_variant", models.CharField(blank=True, max_length=10)),
                (
                    "meal_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="api.dailymealplan",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plan_items",
                        to="api.mealtemplate",
                    ),
                ),
            ],
            options={
                "unique_together": {("meal_plan", "category", "menu_variant")},
            },
        ),
        migrations.CreateModel(
            name="EnrolledCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.PositiveIntegerField(default=0)),
                (
                    "meal_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrolled_counts",
                        to="api.dailymealplan",
                    ),
                ),
                (
                    "portion_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrolled_counts",
                        to="api.portiontype",
                    ),
                ),
            ],
            options={
                "unique_together": {("meal_plan", "portion_type")},
            },
        ),
    ]
