# Generated by Django 5.2.5 on 2026-03-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_globalsettings_deadline_is_day_before"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientsettings",
            name="admin_order_note",
            field=models.TextField(blank=True, default=""),
        ),
    ]
