# Generated by Django 5.1.15 on 2026-05-28 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_seed_default_diets"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealtemplate",
            name="diet",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional diet this template variant is prepared for.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="meal_templates",
                to="api.diet",
            ),
        ),
    ]
