# Generated by Django 5.1.15 on 2026-06-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_userprofile_is_edupage_remove_school"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="billing_name",
            field=models.CharField(
                blank=True, help_text="Názov spoločnosti pre fakturáciu", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="company_name",
            field=models.CharField(
                blank=True,
                help_text="Interný názov prevádzky (používa sa interne)",
                max_length=255,
            ),
        ),
    ]
