# Generated by Django 5.1.15 on 2026-06-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_userprofile_billing_name"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="edupageupload",
            name="api_edupage_date_school_idx",
        ),
        migrations.RenameIndex(
            model_name="edupageupload",
            new_name="api_edupage_date_e27487_idx",
            old_name="api_edupage_date_status_idx",
        ),
        migrations.RenameIndex(
            model_name="jedalnicekentry",
            new_name="api_jedalni_date_5445b3_idx",
            old_name="api_jedal_entry_date_cat_var_idx",
        ),
        migrations.RenameIndex(
            model_name="jedalnicekentry",
            new_name="api_jedalni_date_df27a3_idx",
            old_name="api_jedal_entry_date_diet_idx",
        ),
        migrations.RenameIndex(
            model_name="jedalnicekupload",
            new_name="api_jedalni_week_st_b9a29b_idx",
            old_name="api_jedal_upload_week_status_idx",
        ),
        migrations.RenameIndex(
            model_name="pushnotificationattempt",
            new_name="api_pushnot_user_id_eddf46_idx",
            old_name="api_pushno_user_id_read_at_idx",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="api_identifier",
            field=models.CharField(
                blank=True,
                help_text="Identifier used to match this operation in Edupage file parsing",
                max_length=255,
            ),
        ),
        migrations.AddIndex(
            model_name="edupageupload",
            index=models.Index(
                fields=["date", "operation"], name="api_edupage_date_e8e32b_idx"
            ),
        ),
    ]
