# Generated by Django 5.1.15 on 2026-06-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0032_sync_edupage_jedalnicek_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="mealsguest_url",
            field=models.CharField(
                blank=True,
                help_text="Full mealsGuest URL for HTML scraping, e.g. https://school.edupage.org/menu/mealsGuest?id=TOKEN",
                max_length=500,
            ),
        ),
    ]
