# Generated by Django 5.1.15 on 2026-07-01 17:03

from django.db import migrations, models

_CATEGORY_REMAP = {
    "breakfast": "breakfast_snack",
    "lunch": "main_course",
    "snack": "afternoon_snack",
}


def _remap_categories(apps, schema_editor):
    MealTemplate = apps.get_model("api", "MealTemplate")
    MealPlanItem = apps.get_model("api", "MealPlanItem")
    for old, new in _CATEGORY_REMAP.items():
        MealTemplate.objects.filter(category=old).update(category=new)
        MealPlanItem.objects.filter(category=old).update(category=new)


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_jedalnicekentry_portion_weights"),
    ]

    operations = [
        migrations.RunPython(_remap_categories, _noop_reverse),
        migrations.RemoveField(
            model_name="jedalnicekupload",
            name="uploaded_by",
        ),
        migrations.AddField(
            model_name="mealtemplate",
            name="components",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="mealtemplate",
            name="unit_exception",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mealplanitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("breakfast_snack", "Raňajky-desiata"),
                    ("soup", "Polievka"),
                    ("main_course", "Hlavný chod"),
                    ("afternoon_snack", "Olovrant"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="mealtemplate",
            name="category",
            field=models.CharField(
                choices=[
                    ("breakfast_snack", "Raňajky-desiata"),
                    ("soup", "Polievka"),
                    ("main_course", "Hlavný chod"),
                    ("afternoon_snack", "Olovrant"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="JedalnicekEntry",
        ),
        migrations.DeleteModel(
            name="JedalnicekUpload",
        ),
    ]
