# Generated by Django 5.1.15 on 2026-06-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0035_remove_mealplan_system"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jedalnicekupload",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="jedalnicek_uploads/%Y/%m/"
            ),
        ),
    ]
