# Generated by Codex on 2026-07-08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0038_globalsettings_edupage_auto_scrape_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealplanitem",
            name="diet",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional diet-specific meal plan item. Null means standard/default.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="meal_plan_items",
                to="api.diet",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mealplanitem",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="mealplanitem",
            constraint=models.UniqueConstraint(
                fields=("meal_plan", "category", "menu_variant", "diet"),
                name="uniq_meal_plan_item_slot_diet",
                nulls_distinct=False,
            ),
        ),
    ]
