# Generated by Django 5.1.15 on 2026-07-10 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0039_mealplanitem_diet"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Celok",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazov", models.CharField(max_length=255, unique=True)),
                ("billing_name", models.CharField(blank=True, max_length=255)),
                (
                    "adresa",
                    models.CharField(
                        blank=True, help_text="Fakturačná adresa celku.", max_length=500
                    ),
                ),
                ("ico", models.CharField(blank=True, max_length=20)),
                ("dic", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "ordering": ["nazov"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="dailyorder",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="celok",
            field=models.ForeignKey(
                blank=True,
                help_text="Celok, pod ktorý toto prihlásenie patrí.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="profily",
                to="api.celok",
            ),
        ),
        migrations.CreateModel(
            name="Prevadzka",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nazov",
                    models.CharField(
                        help_text="Názov prevádzky, napr. 'Jolly 1'. Kľúč v DailyOrder.data.",
                        max_length=255,
                    ),
                ),
                (
                    "adresa",
                    models.CharField(
                        blank=True, help_text="Adresa výdajného miesta.", max_length=500
                    ),
                ),
                (
                    "edupage_match",
                    models.CharField(
                        blank=True,
                        help_text="Prefix payer labelu / menu skratky, podľa ktorého sa EduPage riadky priradia tejto prevádzke (napr. 'J1', 'Palisády', 'B - Les').",
                        max_length=255,
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "celok",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prevadzky",
                        to="api.celok",
                    ),
                ),
            ],
            options={
                "ordering": ["celok_id", "sort_order", "nazov"],
            },
        ),
        migrations.AddField(
            model_name="dailyorder",
            name="prevadzka",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="api.prevadzka",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="prevadzky",
            field=models.ManyToManyField(
                blank=True,
                help_text="Prevádzky, ku ktorým má toto prihlásenie prístup. Prázdne = všetky prevádzky celku.",
                related_name="profily",
                to="api.prevadzka",
            ),
        ),
        migrations.AddIndex(
            model_name="dailyorder",
            index=models.Index(
                fields=["prevadzka", "date"], name="api_dailyor_prevadz_505165_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="prevadzka",
            constraint=models.UniqueConstraint(
                fields=("celok", "nazov"), name="unique_prevadzka_nazov_per_celok"
            ),
        ),
    ]
