# Generated by Django 5.1.15 on 2026-07-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0041_backfill_celok_prevadzka"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyorder",
            name="scrape_flags",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Poznámky z posledného EduPage scrapu tejto objednávky, napr. {'attention': [...], 'config_notes': [...]}. Prázdne pri ručných objednávkach a pri scrape bez upozornení.",
            ),
        ),
    ]
