# Generated by Django 5.1.15 on 2026-07-11 17:13

from django.db import migrations, models


def backfill_zdroj_objednavok(apps, schema_editor):
    """Odvoď zdroj celku z existujúcich profilov: EduPage, ak aspoň jeden
    profil celku má is_edupage."""
    Celok = apps.get_model("api", "Celok")
    edupage_celok_ids = (
        apps.get_model("api", "UserProfile")
        .objects.filter(is_edupage=True, celok__isnull=False)
        .values_list("celok_id", flat=True)
        .distinct()
    )
    Celok.objects.filter(pk__in=list(edupage_celok_ids)).update(
        zdroj_objednavok="edupage"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0042_dailyorder_scrape_flags"),
    ]

    operations = [
        migrations.AddField(
            model_name="celok",
            name="zdroj_objednavok",
            field=models.CharField(
                choices=[("app", "Aplikácia"), ("edupage", "EduPage")],
                db_index=True,
                default="app",
                help_text="Odkiaľ chodia objednávky celku: 'edupage' (scraper) alebo 'app' (klient v appke). Určuje zaradenie v admin prehľade dodania podkladov.",
                max_length=16,
            ),
        ),
        migrations.RunPython(backfill_zdroj_objednavok, migrations.RunPython.noop),
    ]
