# Generated by Django 5.1.15 on 2026-07-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0043_celok_zdroj_objednavok"),
    ]

    operations = [
        migrations.AddField(
            model_name="prevadzka",
            name="billing_portion_coefficients",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="{PortionType.name: koeficient} pre počet fakturovaných porcií. Chýbajúci typ = 1.0, teda prázdne {} = beží po hlavách ako doteraz.",
            ),
        ),
    ]
