# Generated by Django 5.1.15 on 2026-07-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0045_edulienka_billing_coefficients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prevadzka",
            name="edupage_match",
            field=models.CharField(
                blank=True,
                help_text="Prefix payer labelu / menu skratky, podľa ktorého sa EduPage riadky priradia tejto prevádzke (napr. 'J1', 'Palisády', 'B - Les'). Viac prefixov oddeľ čiarkou — škola nemá spoločný prefix, jej skupiny sa volajú '1.st', '2.st' aj 'Dospelý' ('1.st, 2.st, Dospelý').",
                max_length=255,
            ),
        ),
    ]
