# Generated by Django 5.1.15 on 2026-07-17 12:46

import django.db.models.deletion
from django.db import migrations, models


def seed_delivery_layout(apps, schema_editor):
    DeliveryBlock = apps.get_model("api", "DeliveryBlock")
    DeliveryRoute = apps.get_model("api", "DeliveryRoute")

    blocks = [
        (
            "Bežné trasy",
            1,
            True,
            False,
            [
                "1.Trasa - Pezinská - Heňo/Ivan",
                "trasa 2 - 9:25 - Ivan/Heňo",
                "TRASA 3 - Jaro",
                "TRASA 4 - MIŇO - 10:00",
                "trasa 5 - RADKO - 10:00",
            ],
        ),
        (
            "Trasa extra",
            2,
            False,
            True,
            [
                "TRASA EXTRA 1 - RENÉ - 9:00",
                "TRASA EXTRA 2 - MIŠO a IGOR 9:15",
                "TRASA EXTRA 3 - DUŠAN - 9:45",
                "TRASA 4 - MAJO - 10:00",
                "TRASA EXTRA ZABALENÉ ZVLÁŠŤ - do 11:00 MAJO",
            ],
        ),
    ]

    for block_name, block_order, main_summary, extra_summary, routes in blocks:
        block, _ = DeliveryBlock.objects.update_or_create(
            name=block_name,
            defaults={
                "sort_order": block_order,
                "include_in_main_summary": main_summary,
                "include_in_extra_summary": extra_summary,
                "is_active": True,
            },
        )
        for route_order, route_name in enumerate(routes, start=1):
            DeliveryRoute.objects.update_or_create(
                block=block,
                name=route_name,
                defaults={"sort_order": route_order, "is_active": True},
            )


def unseed_delivery_layout(apps, schema_editor):
    DeliveryBlock = apps.get_model("api", "DeliveryBlock")
    DeliveryBlock.objects.filter(name__in=["Bežné trasy", "Trasa extra"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0047_edupage_match_semicolon_separator"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("include_in_main_summary", models.BooleanField(default=True)),
                ("include_in_extra_summary", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="diet",
            name="color",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Voliteľná HEX farba pre admin prehľady, napr. #F97316.",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="prevadzka",
            name="delivery_note",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Interná poznámka pre rozvozový/gramážový prehľad.",
            ),
        ),
        migrations.AddField(
            model_name="prevadzka",
            name="delivery_sort_order",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Poradie prevádzky v rámci rozvozovej trasy."
            ),
        ),
        migrations.AddField(
            model_name="prevadzka",
            name="report_alias",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Voliteľný názov v admin Prehľade, ak sa má líšiť od názvu prevádzky.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="prevadzka",
            name="edupage_match",
            field=models.CharField(
                blank=True,
                help_text="Prefix payer labelu / menu skratky, podľa ktorého sa EduPage riadky priradia tejto prevádzke (napr. 'J1', 'Palisády', 'B - Les'). Viac prefixov oddeľ BODKOČIARKOU — škola nemá spoločný prefix, jej skupiny sa volajú '1.st', '2.st' aj 'Dospelý' ('1.st; 2.st; Dospelý'). Čiarka oddeľovač byť nemôže: sama sa vyskytuje v skratkách menu ('mšMal,Hey' je jedna skratka pre dve škôlky).",
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="DeliveryRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("driver", models.CharField(blank=True, default="", max_length=80)),
                ("departure_time", models.TimeField(blank=True, null=True)),
                ("note", models.TextField(blank=True, default="")),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to="api.deliveryblock",
                    ),
                ),
            ],
            options={
                "ordering": ["block__sort_order", "sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="prevadzka",
            name="delivery_route",
            field=models.ForeignKey(
                blank=True,
                help_text="Rozvozová trasa používaná v admin Prehľade.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prevadzky",
                to="api.deliveryroute",
            ),
        ),
        migrations.AddConstraint(
            model_name="deliveryroute",
            constraint=models.UniqueConstraint(
                fields=("block", "name"), name="unique_delivery_route_name_per_block"
            ),
        ),
        migrations.RunPython(seed_delivery_layout, unseed_delivery_layout),
    ]
