# Generated by Django 5.1.15 on 2026-07-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0050_prevadzka_settings_celok_edupage"),
    ]

    operations = [
        migrations.AddField(
            model_name="prevadzka",
            name="pack_separately_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
