# Generated by Django 5.1.15 on 2026-07-24 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0052_diet_sort_order_prevadzka_visible_menus_per_meal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prevadzka",
            name="visible_menus_per_meal",
        ),
    ]
