# Generated by Django 5.1.15 on 2026-07-24 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0053_remove_prevadzka_meal_menu_override"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyorder",
            name="prevadzka",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="api.prevadzka",
            ),
        ),
        migrations.AlterField(
            model_name="dailyorder",
            name="user",
            field=models.ForeignKey(
                help_text="Login, ktorý objednávku naposledy zapísal; môže byť zmazaný.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="prevadzka",
            name="celok",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prevadzky",
                to="api.celok",
            ),
        ),
    ]
