# Generated by Django 5.1.15 on 2026-07-24 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _connection(apps, url, name, api_identifier=""):
    EdupageConnection = apps.get_model("api", "EdupageConnection")
    connection, _ = EdupageConnection.objects.get_or_create(
        mealsguest_url=url,
        defaults={
            "name": name,
            "api_identifier": api_identifier,
        },
    )
    changed = []
    if not connection.name and name:
        connection.name = name
        changed.append("name")
    if not connection.api_identifier and api_identifier:
        connection.api_identifier = api_identifier
        changed.append("api_identifier")
    if changed:
        connection.save(update_fields=changed)
    return connection


def forwards(apps, schema_editor):
    Celok = apps.get_model("api", "Celok")
    EdupageConnection = apps.get_model("api", "EdupageConnection")
    EdupageUpload = apps.get_model("api", "EdupageUpload")
    Prevadzka = apps.get_model("api", "Prevadzka")
    UserProfile = apps.get_model("api", "UserProfile")

    legacy_by_url = {}
    legacy_profiles = (
        UserProfile.objects.exclude(mealsguest_url="")
        .select_related("user")
        .order_by("pk")
    )
    for profile in legacy_profiles:
        legacy_by_url.setdefault(
            profile.mealsguest_url,
            {
                "name": profile.company_name or profile.user.email,
                "api_identifier": profile.api_identifier,
            },
        )

    configured_celky = Celok.objects.exclude(mealsguest_url="").order_by("pk")
    for celok in configured_celky:
        legacy = legacy_by_url.get(celok.mealsguest_url, {})
        connection = _connection(
            apps,
            celok.mealsguest_url,
            legacy.get("name") or celok.nazov,
            legacy.get("api_identifier") or celok.edupage_api_identifier,
        )
        Prevadzka.objects.filter(celok_id=celok.pk).update(
            edupage_connection_id=connection.pk
        )

    for profile in legacy_profiles:
        connection = _connection(
            apps,
            profile.mealsguest_url,
            profile.company_name or profile.user.email,
            profile.api_identifier,
        )
        explicit_ids = list(profile.prevadzky.values_list("pk", flat=True))
        if explicit_ids:
            Prevadzka.objects.filter(
                pk__in=explicit_ids,
                edupage_connection__isnull=True,
            ).update(edupage_connection_id=connection.pk)
        elif profile.celok_id:
            Prevadzka.objects.filter(
                celok_id=profile.celok_id,
                edupage_connection__isnull=True,
            ).update(edupage_connection_id=connection.pk)

    uploads = EdupageUpload.objects.exclude(operation_id=None).select_related(
        "operation"
    )
    for upload in uploads.iterator():
        url = upload.operation.mealsguest_url
        if not url:
            continue
        connection = EdupageConnection.objects.filter(mealsguest_url=url).first()
        if connection is not None:
            upload.connection_id = connection.pk
            upload.save(update_fields=["connection"])


def backwards(apps, schema_editor):
    EdupageConnection = apps.get_model("api", "EdupageConnection")
    EdupageUpload = apps.get_model("api", "EdupageUpload")
    Prevadzka = apps.get_model("api", "Prevadzka")
    EdupageUpload.objects.update(connection=None)
    Prevadzka.objects.update(edupage_connection=None)
    EdupageConnection.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0054_protect_order_history"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EdupageConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("mealsguest_url", models.URLField(max_length=500, unique=True)),
                ("api_identifier", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name", "pk"],
            },
        ),
        migrations.AddField(
            model_name="edupageupload",
            name="connection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploads",
                to="api.edupageconnection",
            ),
        ),
        migrations.AddField(
            model_name="prevadzka",
            name="edupage_connection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prevadzky",
                to="api.edupageconnection",
            ),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.AddIndex(
            model_name="edupageupload",
            index=models.Index(
                fields=["date", "connection"], name="api_edupage_date_3c3175_idx"
            ),
        ),
    ]
