# Generated by Django 5.1.15 on 2026-07-24 12:51

import django.db.models.deletion
from django.db import migrations, models


def forwards(apps, schema_editor):
    UserProfile = apps.get_model("api", "UserProfile")
    ProfileCelokAccess = apps.get_model("api", "ProfileCelokAccess")
    ProfilePrevadzkaAccess = apps.get_model("api", "ProfilePrevadzkaAccess")

    celok_accesses = []
    prevadzka_accesses = []
    profiles = UserProfile.objects.prefetch_related("prevadzky").iterator(
        chunk_size=500
    )
    for profile in profiles:
        prevadzka_ids = list(profile.prevadzky.values_list("id", flat=True))
        if prevadzka_ids:
            prevadzka_accesses.extend(
                ProfilePrevadzkaAccess(
                    profile_id=profile.id,
                    prevadzka_id=prevadzka_id,
                )
                for prevadzka_id in prevadzka_ids
            )
        elif profile.celok_id:
            celok_accesses.append(
                ProfileCelokAccess(
                    profile_id=profile.id,
                    celok_id=profile.celok_id,
                )
            )

    ProfileCelokAccess.objects.bulk_create(celok_accesses, ignore_conflicts=True)
    ProfilePrevadzkaAccess.objects.bulk_create(
        prevadzka_accesses,
        ignore_conflicts=True,
    )


def backwards(apps, schema_editor):
    apps.get_model("api", "ProfileCelokAccess").objects.all().delete()
    apps.get_model("api", "ProfilePrevadzkaAccess").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0055_edupage_connection_expand"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileCelokAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "celok",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_accesses",
                        to="api.celok",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="celok_accesses",
                        to="api.userprofile",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("profile", "celok"), name="unique_profile_celok_access"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProfilePrevadzkaAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prevadzka",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_accesses",
                        to="api.prevadzka",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prevadzka_accesses",
                        to="api.userprofile",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("profile", "prevadzka"),
                        name="unique_profile_prevadzka_access",
                    )
                ],
            },
        ),
        migrations.RunPython(forwards, backwards),
    ]
