# Generated by Django 5.1.15 on 2026-07-24 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0056_explicit_profile_access"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientsettings",
            name="user",
        ),
        migrations.RemoveField(
            model_name="clientsettings",
            name="visible_diets",
        ),
        migrations.RemoveIndex(
            model_name="edupageupload",
            name="api_edupage_date_e8e32b_idx",
        ),
        migrations.RemoveField(
            model_name="celok",
            name="edupage_api_identifier",
        ),
        migrations.RemoveField(
            model_name="celok",
            name="mealsguest_url",
        ),
        migrations.RemoveField(
            model_name="edupageupload",
            name="operation",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="api_identifier",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="billing_name",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="celok",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="dic",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="ico",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="is_edupage",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="mealsguest_url",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="prevadzky",
        ),
        migrations.DeleteModel(
            name="ClientSettings",
        ),
    ]
