# Generated by Django 5.1.15 on 2026-07-24 15:03

from django.db import migrations


def _settings_owner(UserProfile, prevadzka):
    profile = prevadzka.profily.order_by("pk").first()
    if profile is None:
        profile = (
            UserProfile.objects.filter(
                celok_id=prevadzka.celok_id,
                prevadzky__isnull=True,
            )
            .order_by("pk")
            .first()
        )
    if profile is None:
        profile = (
            UserProfile.objects.filter(celok_id=prevadzka.celok_id)
            .order_by("pk")
            .first()
        )
    return profile


def _billing_owner(UserProfile, celok):
    profile = (
        UserProfile.objects.filter(prevadzky__celok_id=celok.pk).order_by("pk").first()
    )
    if profile is None:
        profile = (
            UserProfile.objects.filter(
                celok_id=celok.pk,
                prevadzky__isnull=True,
            )
            .order_by("pk")
            .first()
        )
    if profile is None:
        profile = UserProfile.objects.filter(celok_id=celok.pk).order_by("pk").first()
    return profile


def final_legacy_backfill(apps, schema_editor):
    Celok = apps.get_model("api", "Celok")
    ClientSettings = apps.get_model("api", "ClientSettings")
    Prevadzka = apps.get_model("api", "Prevadzka")
    UserProfile = apps.get_model("api", "UserProfile")

    for prevadzka in Prevadzka.objects.all().iterator():
        profile = _settings_owner(UserProfile, prevadzka)
        if profile is None:
            continue

        settings = ClientSettings.objects.filter(user_id=profile.user_id).first()
        if settings is None:
            continue

        prevadzka.visible_menus = settings.visible_menus or ["A"]
        prevadzka.visible_meals = settings.visible_meals or [
            "breakfast",
            "lunch",
            "olovrant",
        ]
        prevadzka.admin_order_note = settings.admin_order_note or ""
        prevadzka.save(
            update_fields=["visible_menus", "visible_meals", "admin_order_note"]
        )
        prevadzka.visible_diets.set(settings.visible_diets.all())

    for celok in Celok.objects.all().iterator():
        profile = _billing_owner(UserProfile, celok)
        if profile is None:
            continue
        celok.billing_name = profile.billing_name
        celok.ico = profile.ico
        celok.dic = profile.dic
        celok.save(update_fields=["billing_name", "ico", "dic"])


contract_state_operations = [
    migrations.RemoveField(
        model_name="clientsettings",
        name="user",
    ),
    migrations.RemoveField(
        model_name="clientsettings",
        name="visible_diets",
    ),
    migrations.RemoveIndex(
        model_name="edupageupload",
        name="api_edupage_date_e8e32b_idx",
    ),
    migrations.RemoveField(
        model_name="celok",
        name="edupage_api_identifier",
    ),
    migrations.RemoveField(
        model_name="celok",
        name="mealsguest_url",
    ),
    migrations.RemoveField(
        model_name="edupageupload",
        name="operation",
    ),
    migrations.RemoveField(
        model_name="userprofile",
        name="api_identifier",
    ),
    migrations.RemoveField(
        model_name="userprofile",
        name="billing_name",
    ),
    migrations.RemoveField(
        model_name="userprofile",
        name="celok",
    ),
    migrations.RemoveField(
        model_name="userprofile",
        name="dic",
    ),
    migrations.RemoveField(
        model_name="userprofile",
        name="ico",
    ),
    migrations.RemoveField(
        model_name="userprofile",
        name="is_edupage",
    ),
    migrations.RemoveField(
        model_name="userprofile",
        name="mealsguest_url",
    ),
    migrations.RemoveField(
        model_name="userprofile",
        name="prevadzky",
    ),
    migrations.DeleteModel(
        name="ClientSettings",
    ),
]

legacy_insert_defaults = migrations.RunSQL(
    sql=[
        (
            """
            ALTER TABLE api_userprofile
                ALTER COLUMN api_identifier SET DEFAULT '',
                ALTER COLUMN billing_name SET DEFAULT '',
                ALTER COLUMN dic SET DEFAULT '',
                ALTER COLUMN ico SET DEFAULT '',
                ALTER COLUMN is_edupage SET DEFAULT false,
                ALTER COLUMN mealsguest_url SET DEFAULT '';
            """,
            None,
        ),
        (
            """
            ALTER TABLE api_celok
                ALTER COLUMN edupage_api_identifier SET DEFAULT '',
                ALTER COLUMN mealsguest_url SET DEFAULT '';
            """,
            None,
        ),
    ],
    reverse_sql=[
        (
            """
            ALTER TABLE api_userprofile
                ALTER COLUMN api_identifier DROP DEFAULT,
                ALTER COLUMN billing_name DROP DEFAULT,
                ALTER COLUMN dic DROP DEFAULT,
                ALTER COLUMN ico DROP DEFAULT,
                ALTER COLUMN is_edupage DROP DEFAULT,
                ALTER COLUMN mealsguest_url DROP DEFAULT;
            """,
            None,
        ),
        (
            """
            ALTER TABLE api_celok
                ALTER COLUMN edupage_api_identifier DROP DEFAULT,
                ALTER COLUMN mealsguest_url DROP DEFAULT;
            """,
            None,
        ),
    ],
)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0056_explicit_profile_access"),
    ]

    operations = [
        migrations.RunPython(final_legacy_backfill, migrations.RunPython.noop),
        migrations.SeparateDatabaseAndState(
            database_operations=[legacy_insert_defaults],
            state_operations=contract_state_operations,
        ),
    ]
