# Generated by Django 5.1.15 on 2026-07-24

from django.db import migrations


def delete_uploaded_files(apps, schema_editor):
    EdupageUpload = apps.get_model("api", "EdupageUpload")
    for upload in EdupageUpload.objects.only("file").iterator():
        if upload.file:
            upload.file.delete(save=False)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0057_remove_legacy_facility_models"),
    ]

    operations = [
        migrations.RunPython(delete_uploaded_files, migrations.RunPython.noop),
        migrations.DeleteModel(
            name="EdupageUpload",
        ),
    ]
