# Generated by Django 5.1.15 on 2026-07-24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0057_remove_legacy_facility_models"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name="EdupageUpload",
                ),
            ],
        ),
    ]
