# Generated by Django 5.0.14 on 2026-08-02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0059_fix_legacy_contract_delete_constraints"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("order_admin_create", "Admin vytvoril objednávku"),
                            ("order_admin_update", "Admin upravil objednávku"),
                            ("auto_order_run", "Spustenie auto-objednávok"),
                            ("push_broadcast", "Odoslanie push notifikácie"),
                            ("settings_change", "Zmena nastavení"),
                        ],
                        max_length=50,
                    ),
                ),
                ("actor_label", models.CharField(blank=True, max_length=255)),
                ("summary", models.CharField(max_length=255)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="event_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="targeted_event_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="api_eventlo_created_c80454_idx"
                    ),
                    models.Index(
                        fields=["event_type"], name="api_eventlo_event_t_bbb685_idx"
                    ),
                    models.Index(
                        fields=["actor"], name="api_eventlo_actor_i_17598f_idx"
                    ),
                    models.Index(
                        fields=["target_user"], name="api_eventlo_target__c47ada_idx"
                    ),
                ],
            },
        ),
    ]
