# Generated by Django 5.1.15 on 2026-08-07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0062_closedday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventlog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("order_admin_create", "Admin vytvoril objednávku"),
                    ("order_admin_update", "Admin upravil objednávku"),
                    ("order_admin_delete", "Admin vymazal objednávku"),
                    ("auto_order_run", "Spustenie auto-objednávok"),
                    ("push_broadcast", "Odoslanie push notifikácie"),
                    ("settings_change", "Zmena nastavení"),
                ],
                max_length=50,
            ),
        ),
    ]
