# Generated by Django 5.1.15 on 2026-08-07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0063_alter_eventlog_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="diet",
            name="base_diets",
            field=models.ManyToManyField(
                blank=True,
                related_name="composite_of",
                symmetrical=False,
                to="api.diet",
            ),
        ),
    ]
