# Generated by Django 5.1.15 on 2026-08-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0067_globalsettings_daily_report_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventlog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("order_admin_create", "Admin vytvoril objednávku"),
                    ("order_admin_update", "Admin upravil objednávku"),
                    ("order_admin_delete", "Admin vymazal objednávku"),
                    ("auto_order_run", "Spustenie auto-objednávok"),
                    ("push_broadcast", "Odoslanie push notifikácie"),
                    ("settings_change", "Zmena nastavení"),
                    ("cron_run", "Cron úloha dobehla"),
                    ("cron_skipped", "Cron úloha preskočená (víkend/voľný deň)"),
                    ("cron_failed", "Cron úloha zlyhala"),
                    ("deploy_version", "Nasadená nová verzia"),
                ],
                max_length=50,
            ),
        ),
    ]
