# Generated by Django 5.1.15 on 2026-08-15 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # Prečíslované pri integrácii: rolová vetva obsadila 0069–0073.
        ("api", "0076_demote_admins_to_admin_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrevadzkaClosure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_from", models.DateField(db_index=True)),
                ("date_to", models.DateField(db_index=True)),
                ("reason", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prevadzka",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="closures",
                        to="api.prevadzka",
                    ),
                ),
            ],
            options={
                "verbose_name": "voľno prevádzky",
                "verbose_name_plural": "voľná prevádzky",
                "ordering": ["-date_from", "prevadzka_id"],
                "indexes": [
                    models.Index(
                        fields=["prevadzka", "date_from", "date_to"],
                        name="prevadzka_closure_lookup",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("date_to__gte", models.F("date_from"))),
                        name="prevadzka_closure_range_ordered",
                    )
                ],
            },
        ),
    ]
