# Generated by Django 5.1.15 on 2026-08-30 16:03

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0080_alter_dailyorder_scrape_flags"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalsettings",
            name="deadline_menu_bc",
            field=models.TimeField(
                default=datetime.time(7, 30),
                help_text="Deadline for ordering/changing menu B and C, N days before the meal date",
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="deadline_menu_bc_days_before",
            field=models.PositiveSmallIntegerField(
                default=2,
                help_text="How many days before the meal date the menu B/C deadline falls on",
            ),
        ),
    ]
