# Generated by Django 5.1.15 on 2026-08-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0081_globalsettings_deadline_menu_bc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prevadzka",
            name="auto_order_paused",
            field=models.BooleanField(
                default=False,
                help_text="Nastaví sa automaticky, keď klient vynuluje alebo zmaže objednávku (prázdne 'submitted' dáta, alebo 'draft'). Kým je True, apply_auto_orders pre túto prevádzku nič nepreklápa — obnoví sa opäť False pri najbližšej reálnej (neprázdnej) objednávke.",
            ),
        ),
    ]
