# Generated by Django 5.1.15 on 2026-08-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0082_prevadzka_auto_order_paused"),
    ]

    operations = [
        migrations.AddField(
            model_name="prevadzka",
            name="olovrant_s_obedom",
            field=models.BooleanField(
                default=False,
                help_text="Olovrant tejto prevádzky ide s obedovým, nie popoludňajším rozvozom — v gramážnej tabuľke (aj v PDF) sa preto zvýrazní žlto, aby si ho kuchyňa naložila spolu s obedom.",
            ),
        ),
    ]
