# Generated by Django 5.1.15 on 2026-08-31 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0083_prevadzka_olovrant_s_obedom"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalsettings",
            name="edupage_scrape_time_breakfast",
            field=models.TimeField(
                blank=True,
                help_text="Override: scrape breakfast EduPage orders at this time instead of at deadline_breakfast. Leave empty to keep scraping at the deadline.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="edupage_scrape_time_breakfast_is_day_before",
            field=models.BooleanField(
                default=False,
                help_text="Only used when edupage_scrape_time_breakfast is set: whether that override time targets the next workday (like a day-before deadline) or today. Independent of deadline_breakfast_is_day_before, because an override commonly runs after midnight — already on the meal's own day — even though the deadline itself falls the evening before.",
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="edupage_scrape_time_lunch",
            field=models.TimeField(
                blank=True,
                help_text="Override: scrape lunch EduPage orders at this time instead of at deadline_lunch. Leave empty to keep scraping at the deadline.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="edupage_scrape_time_lunch_is_day_before",
            field=models.BooleanField(
                default=False,
                help_text="Only used when edupage_scrape_time_lunch is set. See edupage_scrape_time_breakfast_is_day_before.",
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="edupage_scrape_time_olovrant",
            field=models.TimeField(
                blank=True,
                help_text="Override: scrape olovrant EduPage orders at this time instead of at deadline_olovrant. Leave empty to keep scraping at the deadline.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="edupage_scrape_time_olovrant_is_day_before",
            field=models.BooleanField(
                default=False,
                help_text="Only used when edupage_scrape_time_olovrant is set. See edupage_scrape_time_breakfast_is_day_before.",
            ),
        ),
    ]
