# Generated by Django 5.1.15 on 2026-08-31 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0085_default_edupage_scrape_times"),
    ]

    operations = [
        migrations.AddField(
            model_name="edupageconnection",
            name="dedicated_scrape_hour",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Set together with dedicated_scrape_minute to scrape this connection on its own crontab (day before, Sun-Thu, targeting the next workday) instead of at the shared GlobalSettings meal deadlines every other connection uses. For a facility whose deadline schedule genuinely doesn't apply, e.g. British School (#535) — code review 2026-08-31 generalized this off a hardcoded connection name.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="edupageconnection",
            name="dedicated_scrape_minute",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
