# Generated by Django 5.1.15 on 2026-09-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0089_seed_skolicka_speci_diet"),
    ]

    operations = [
        migrations.AddField(
            model_name="prevadzka",
            name="menu_day_restrictions",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='{menu písmeno: [ISO deň v týždni, 1=pondelok..7=nedeľa]} — obmedzenie, kedy sa dané menu (z visible_menus) dá objednať, napr. menu B len v piatok = {"B": [5]}. Chýbajúci kľúč alebo prázdny zoznam = každý deň.',
            ),
        ),
    ]
