# Generated by Django 5.1.15 on 2026-09-01 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0090_prevadzka_menu_day_restrictions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="eventlog",
            name="prevadzka",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="event_logs",
                to="api.prevadzka",
            ),
        ),
        migrations.AlterField(
            model_name="eventlog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("order_admin_create", "Objednávka vytvorená"),
                    ("order_admin_update", "Objednávka upravená"),
                    ("order_admin_delete", "Objednávka vymazaná"),
                    ("auto_order_run", "Spustenie auto-objednávok"),
                    ("push_broadcast", "Odoslanie push notifikácie"),
                    ("settings_change", "Zmena nastavení"),
                    ("cron_run", "Cron úloha dobehla"),
                    ("cron_skipped", "Cron úloha preskočená (víkend/voľný deň)"),
                    ("cron_failed", "Cron úloha zlyhala"),
                    ("deploy_version", "Nasadená nová verzia"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="eventlog",
            index=models.Index(
                fields=["prevadzka"], name="api_eventlo_prevadz_4df86b_idx"
            ),
        ),
    ]
