# Generated by Django 5.1.15 on 2026-09-03 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0092_alter_closedday_closed_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="prevadzka",
            name="auto_order_breakfast_source",
            field=models.CharField(
                choices=[("breakfast", "Raňajky"), ("lunch", "Obed")],
                default="breakfast",
                help_text=(
                    "Z ktorého chodu predošlého dňa apply_auto_orders naplní "
                    "raňajky. Default 'breakfast' = raňajky sa kopírujú z "
                    "predošlých raňajok. 'lunch' = raňajky sa namiesto toho "
                    "naplnia predošlým obedom (napr. Bystrá škôlky, kde sa "
                    "raňajky objednávajú ako obed z predošlého dňa)."
                ),
                max_length=20,
            ),
        ),
    ]
