# Generated by Django 5.1.15 on 2026-09-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0093_prevadzka_auto_order_breakfast_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="prevadzka",
            name="adults_pack_separately_enabled",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Keď je zapnuté, všetky porcie „Dospelý (SŠ)“ sa v gramážnej "
                    "tabuľke automaticky vykazujú ako zabalené zvlášť — bez toho, "
                    "aby ich klient musel manuálne označiť cez „Zabaliť zvlášť“."
                ),
            ),
        ),
    ]
