# Generated by Django 5.1.15 on 2026-09-04 11:54

import django.db.models.deletion
from django.db import migrations, models


def copy_visible_diets_to_through_table(apps, schema_editor):
    """`visible_diets` bola dosiaľ implicitné M2M — Django pri prechode na
    explicitný `through` model (nasledujúci AlterField) dáta z pôvodnej
    auto-generovanej tabuľky `api_prevadzka_visible_diets` neprenesie samo.
    Skopíruj existujúce priradenia (s prázdnou poznámkou), kým je stará
    tabuľka ešte dostupná — inak by po tejto migrácii všetky prevádzky
    ostali bez povolených diét."""
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT to_regclass('public.api_prevadzka_visible_diets')
            """)
        (old_table,) = cursor.fetchone()
        if not old_table:
            return
        cursor.execute("""
            INSERT INTO api_prevadzkadiet (prevadzka_id, diet_id, note)
            SELECT prevadzka_id, diet_id, ''
            FROM api_prevadzka_visible_diets
            ON CONFLICT DO NOTHING
            """)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0094_prevadzka_adults_pack_separately_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrevadzkaDiet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                (
                    "diet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prevadzka_diets",
                        to="api.diet",
                    ),
                ),
                (
                    "prevadzka",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prevadzka_diets",
                        to="api.prevadzka",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="prevadzkadiet",
            constraint=models.UniqueConstraint(
                fields=("prevadzka", "diet"), name="unique_prevadzka_diet"
            ),
        ),
        migrations.RunPython(
            copy_visible_diets_to_through_table, migrations.RunPython.noop
        ),
        # Django nedovolí AlterField pridať `through=` na existujúci M2M cez
        # bežný schema_editor ("cannot alter to or from M2M fields") — DB
        # tabuľka pre nový through model už existuje (CreateModel vyššie) a
        # dáta sú skopírované, takže tu ide len o zmenu ORM stavu, nie DB.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="prevadzka",
                    name="visible_diets",
                    field=models.ManyToManyField(
                        blank=True,
                        help_text="Diéty dostupné pre objednávky tejto prevádzky.",
                        related_name="visible_for_prevadzky",
                        through="api.PrevadzkaDiet",
                        to="api.diet",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
