# Generated manually — follow-up to 0095.

from django.db import migrations


def _table_exists(schema_editor, table_name: str) -> bool:
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT to_regclass(%s)", [f"public.{table_name}"])
        (existing,) = cursor.fetchone()
        return bool(existing)


def drop_old_visible_diets_table(apps, schema_editor):
    """0095 converted `visible_diets` from an implicit M2M to an explicit
    `PrevadzkaDiet` through model and copied the data across, but left the
    old auto-generated table (`api_prevadzka_visible_diets`) in place —
    Django no longer manages it, yet Postgres still enforces its FK to
    `api_prevadzka(id)`. That orphaned constraint then blocks deleting any
    Prevádzka that ever had a diet assigned (`ForeignKeyViolation`), which
    broke `seed_merge_celky`'s retirement of old prevádzky and crashed the
    backend container on startup. Drop it now that 0095 has verified data
    lives in `api_prevadzkadiet`.
    """
    if schema_editor.connection.vendor != "postgresql":
        return
    if not _table_exists(schema_editor, "api_prevadzka_visible_diets"):
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DROP TABLE api_prevadzka_visible_diets")


def recreate_old_visible_diets_table(apps, schema_editor):
    """Reverse of the above — needed for real reversibility, not cosmetic:
    `tests/test_legacy_contract_migration.py` walks the *entire* migration
    history backwards past this point, and older migrations (e.g. 0089's
    `remove_diet`) delete `Diet` rows, which cascades into this table via
    the model state Django reconstructs for that historical point — a state
    where `visible_diets` is still the old implicit M2M. Without recreating
    the table here, that cascade hits a table that no longer exists.

    0095 hasn't been reversed yet at this point in the backward walk, so
    `api_prevadzkadiet` (the through table) is still around — carry its
    rows back into the recreated legacy table so the two stay consistent
    through the round trip.
    """
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS api_prevadzka_visible_diets (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                prevadzka_id bigint NOT NULL
                    REFERENCES api_prevadzka (id) DEFERRABLE INITIALLY DEFERRED,
                diet_id bigint NOT NULL
                    REFERENCES api_diet (id) DEFERRABLE INITIALLY DEFERRED,
                CONSTRAINT api_prevadzka_visible_diets_prevadzka_id_diet_id_4bc3b9f5_uniq
                    UNIQUE (prevadzka_id, diet_id)
            )
            """)
        cursor.execute(
            "CREATE INDEX IF NOT EXISTS api_prevadzka_visible_diets_prevadzka_id_46fe907a "
            "ON api_prevadzka_visible_diets (prevadzka_id)"
        )
        cursor.execute(
            "CREATE INDEX IF NOT EXISTS api_prevadzka_visible_diets_diet_id_2302a3dc "
            "ON api_prevadzka_visible_diets (diet_id)"
        )
        cursor.execute("""
            SELECT to_regclass('public.api_prevadzkadiet')
            """)
        (through_table,) = cursor.fetchone()
        if through_table:
            cursor.execute("""
                INSERT INTO api_prevadzka_visible_diets (prevadzka_id, diet_id)
                SELECT prevadzka_id, diet_id FROM api_prevadzkadiet
                ON CONFLICT DO NOTHING
                """)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0095_prevadzkadiet_alter_prevadzka_visible_diets_and_more"),
    ]

    operations = [
        migrations.RunPython(
            drop_old_visible_diets_table, recreate_old_visible_diets_table
        ),
    ]
