repos:
  - repo: local
    hooks:
      - id: backend-pytest-coverage
        name: backend pytest coverage >= 60%
        entry: bash -c 'cd backend && /home/tomas-magula/Documents/Projects/ZB/zdravy-projekt/backend/.venv/bin/pytest --cov=api --cov=app --cov-config=.coveragerc --cov-report=term-missing --cov-report=html --cov-fail-under=60'
        language: system
        pass_filenames: false
        stages: [pre-commit]
