[pytest]
DJANGO_SETTINGS_MODULE = app.settings.dev
python_files = tests.py test_*.py *_tests.py
addopts = 
    --reuse-db
    --nomigrations
    --cov=app
    --cov-report=term-missing
    --cov-report=html
