http:
  routers:
    dokploy-webhook:
      # Staging-specific host.
      # If domain changes, update this value or create a separate per-environment file.
      rule: "Host(`zp.tomag.xyz`) && PathPrefix(`/api/deploy/compose/`)"
      entryPoints:
        - web
        - websecure
      service: dokploy-api
      priority: 1000

  services:
    dokploy-api:
      loadBalancer:
        servers:
          - url: "http://dokploy:3000"
