"""
Parser for the Jedálniček XLSX input template.

The template structure (generated by scripts/generate_jedalnicky_template.py):

  Sheet "INŠTRUKCIE":
    B3 = year (int)
    B4 = week number (int)
    B5 = date_from string "DD.MM.YYYY"
    B6 = date_to string "DD.MM.YYYY"

  Per-diet sheets (e.g. "Klasik", "Vege", "No Gluten" …):
    Row 1  – title: "JEDÁLNIČEK – KLASIK"
    Row 2  – column headers (skipped by parser)
    Row 3+ – data:
      Day rows   : col A = "  PONDELOK" (stripped → known day name), cols B-G merged/None
      Meal rows  : col A = None, col B = meal-type label, cols C-G merged/None
      Ingredient : col A = None, col B = None, col C = component name,
                   col D = allergens,
                   cols E+ = amounts per portion (Množstvo Škôlka ...),
                   next col = unit (g/ks),
                   optional final col = notes
      Separator  : all None — skipped

Usage:
    from api.parsers.jedalnicek_xlsx_parser import JedalnicekXlsxParser

    with open("template.xlsx", "rb") as f:
        result = JedalnicekXlsxParser().parse(f)

    if result.ok:
        for row in result.rows:
            print(row.date, row.diet_sheet, row.component_name, row.amount, row.unit)
    else:
        print("Errors:", result.errors)
"""

import datetime
import io
import logging
from dataclasses import dataclass, field
from decimal import Decimal, InvalidOperation
from typing import BinaryIO, List, Optional, Union

logger = logging.getLogger(__name__)

# ── constants ─────────────────────────────────────────────────────────────────

INSTRUKCIE_SHEET = "INŠTRUKCIE"

DAY_NAMES = ["PONDELOK", "UTOROK", "STREDA", "ŠTVRTOK", "PIATOK"]
DAY_OFFSET: dict[str, int] = {day: i for i, day in enumerate(DAY_NAMES)}

# Maps the label shown in column B to (MealCategory value, menu_variant)
MEAL_TYPE_MAP: dict[str, tuple[str, str]] = {
    "Raňajky-desiata": ("breakfast", ""),
    "Polievka": ("lunch", "P"),
    "Obed (Menu A)": ("lunch", "A"),
    "Obed (Menu B)": ("lunch", "B"),
    "Obed (Menu C)": ("lunch", "C"),
    "Olovrant": ("snack", ""),
}

DEFAULT_UNIT = "g"
VALID_UNITS = {"g", "ks"}


# ── result types ──────────────────────────────────────────────────────────────


@dataclass
class ParsedRow:
    date: datetime.date
    diet_sheet: str
    category: str  # MealCategory value: "breakfast" | "lunch" | "snack"
    menu_variant: str  # "" | "A" | "B" | "C" | "P"
    component_name: str
    allergens: str
    amount: Optional[Decimal]
    unit: str  # "g" | "ks"
    notes: str = ""
    portion_amounts: dict[str, Decimal] = field(default_factory=dict)


@dataclass
class ParseResult:
    week_year: int
    week_number: int
    week_start: datetime.date
    week_end: datetime.date
    rows: List[ParsedRow] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)
    errors: List[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return len(self.errors) == 0


@dataclass(frozen=True)
class SheetLayout:
    amount_columns: list[tuple[str, int]]
    unit_index: int
    notes_index: int | None


# ── parser ────────────────────────────────────────────────────────────────────


class JedalnicekXlsxParser:
    """
    Stateless parser — safe to reuse across calls.
    Never raises; all problems are captured in ParseResult.errors / .warnings.
    """

    def parse(self, source: Union[str, BinaryIO, bytes]) -> ParseResult:
        try:
            import openpyxl
        except ImportError as exc:  # pragma: no cover
            return _fatal(f"openpyxl not installed: {exc}")

        logger.info("JedalnicekXlsxParser: opening workbook")

        try:
            if isinstance(source, (str,)):
                wb = openpyxl.load_workbook(source, data_only=True, read_only=True)
            elif isinstance(source, (bytes, bytearray)):
                wb = openpyxl.load_workbook(
                    io.BytesIO(source), data_only=True, read_only=True
                )
            else:
                wb = openpyxl.load_workbook(source, data_only=True, read_only=True)
        except Exception as exc:
            logger.error("Cannot open workbook: %s", exc)
            return _fatal(f"Nepodarilo sa otvoriť xlsx súbor: {exc}")

        # ── metadata ──────────────────────────────────────────────────────────
        result = self._parse_metadata(wb)
        if not result.ok:
            return result

        # ── diet sheets ───────────────────────────────────────────────────────
        for sheet_name in wb.sheetnames:
            if sheet_name == INSTRUKCIE_SHEET:
                continue
            logger.debug("Parsing diet sheet: %s", sheet_name)
            ws = wb[sheet_name]
            rows = self._parse_diet_sheet(
                ws, sheet_name, result.week_start, result.warnings
            )
            result.rows.extend(rows)
            logger.info("Sheet '%s': %d ingredient rows parsed", sheet_name, len(rows))

        logger.info(
            "Parse complete — %d total rows, %d warnings, %d errors",
            len(result.rows),
            len(result.warnings),
            len(result.errors),
        )
        return result

    # ── metadata ──────────────────────────────────────────────────────────────

    def _parse_metadata(self, wb) -> ParseResult:
        if INSTRUKCIE_SHEET not in wb.sheetnames:
            msg = (
                f"Chýba povinný list '{INSTRUKCIE_SHEET}' — nie je možné určiť týždeň."
            )
            logger.error(msg)
            return _fatal(msg)

        ws = wb[INSTRUKCIE_SHEET]
        raw_year = _cell_val(ws, 3, 2)
        raw_week = _cell_val(ws, 4, 2)
        raw_date_from = _cell_val(ws, 5, 2)
        raw_date_to = _cell_val(ws, 6, 2)

        errors: List[str] = []
        warnings: List[str] = []

        year = _coerce_int(raw_year)
        if year is None:
            errors.append(f"Chýba alebo neplatná hodnota Rok (bunka B3): {raw_year!r}")
            logger.error("Missing or invalid year in B3: %r", raw_year)

        week = _coerce_int(raw_week)
        if week is None:
            errors.append(
                f"Chýba alebo neplatná hodnota Týždeň (bunka B4): {raw_week!r}"
            )
            logger.error("Missing or invalid week in B4: %r", raw_week)

        if errors:
            result = ParseResult(
                week_year=0,
                week_number=0,
                week_start=datetime.date.min,
                week_end=datetime.date.min,
            )
            result.errors.extend(errors)
            return result

        assert year is not None
        assert week is not None

        try:
            week_start = datetime.date.fromisocalendar(year, week, 1)
            week_end = datetime.date.fromisocalendar(year, week, 5)
        except ValueError as exc:
            msg = f"Neplatný rok/týždeň ({year}/{week}): {exc}"
            logger.error(msg)
            return _fatal(msg)

        logger.info(
            "Week metadata: year=%d week=%d start=%s end=%s",
            year,
            week,
            week_start,
            week_end,
        )

        # Sanity-check the stored date strings
        stored_from = _parse_date_str(raw_date_from)
        stored_to = _parse_date_str(raw_date_to)
        if stored_from and stored_from != week_start:
            msg = (
                f"Dátum od v šablóne ({stored_from}) nezodpovedá vypočítanému "
                f"začiatku týždňa {week}/{year} ({week_start})."
            )
            warnings.append(msg)
            logger.warning(msg)
        if stored_to and stored_to != week_end:
            msg = (
                f"Dátum do v šablóne ({stored_to}) nezodpovedá vypočítanému "
                f"koncu týždňa {week}/{year} ({week_end})."
            )
            warnings.append(msg)
            logger.warning(msg)

        result = ParseResult(
            week_year=year, week_number=week, week_start=week_start, week_end=week_end
        )
        result.warnings.extend(warnings)
        return result

    # ── diet sheet ────────────────────────────────────────────────────────────

    def _parse_diet_sheet(
        self,
        ws,
        diet_name: str,
        week_start: datetime.date,
        warnings: List[str],
    ) -> List[ParsedRow]:
        rows: List[ParsedRow] = []
        current_date: Optional[datetime.date] = None
        current_category: Optional[str] = None
        current_variant: Optional[str] = None
        layout = _sheet_layout(ws)

        for excel_row in ws.iter_rows(min_row=3, values_only=True):
            col_a = _str(excel_row[0] if len(excel_row) > 0 else None)
            col_b = _str(excel_row[1] if len(excel_row) > 1 else None)
            col_c = _str(excel_row[2] if len(excel_row) > 2 else None)
            col_d = _str(excel_row[3] if len(excel_row) > 3 else None)
            unit_raw = _str(
                excel_row[layout.unit_index]
                if len(excel_row) > layout.unit_index
                else None
            )
            notes = _str(
                excel_row[layout.notes_index]
                if layout.notes_index is not None
                and len(excel_row) > layout.notes_index
                else None
            )

            day_candidate = col_a.strip()
            meal_candidate = col_b.strip()

            # ── day row ───────────────────────────────────────────────────────
            if day_candidate in DAY_NAMES:
                current_date = week_start + datetime.timedelta(
                    days=DAY_OFFSET[day_candidate]
                )
                current_category = None
                current_variant = None
                logger.debug("  Day: %s → %s", day_candidate, current_date)
                continue

            # Day cell has content but it's not a known day name → warn and skip block
            if col_a:
                msg = (
                    f"Neznámy názov dňa '{col_a}' v liste '{diet_name}' "
                    f"— riadky tohto dňa budú preskočené."
                )
                warnings.append(msg)
                logger.warning(msg)
                current_date = None
                current_category = None
                current_variant = None
                continue

            # ── meal type row ─────────────────────────────────────────────────
            if meal_candidate in MEAL_TYPE_MAP:
                current_category, current_variant = MEAL_TYPE_MAP[meal_candidate]
                logger.debug(
                    "    Meal type: %s → %s/%s",
                    meal_candidate,
                    current_category,
                    current_variant,
                )
                continue

            if col_b and meal_candidate not in MEAL_TYPE_MAP:
                msg = (
                    f"Neznámy typ chodu '{col_b}' v liste '{diet_name}' "
                    f"— nasledujúce ingrediencie budú preskočené."
                )
                warnings.append(msg)
                logger.warning(msg)
                current_category = None
                current_variant = None
                continue

            # ── ingredient row ────────────────────────────────────────────────
            if col_c:
                if current_date is None:
                    # Ingredient arrived before any recognised day row — skip
                    continue

                if current_category is None:
                    msg = (
                        f"Ingrediencia '{col_c}' v liste '{diet_name}' "
                        f"nemá priradený chod (chýba riadok s typom chodu)."
                    )
                    warnings.append(msg)
                    logger.warning(msg)
                    continue

                portion_amounts: dict[str, Decimal] = {}
                for portion_name, amount_index in layout.amount_columns:
                    raw_amount = (
                        excel_row[amount_index]
                        if len(excel_row) > amount_index
                        else None
                    )
                    amount = _parse_amount(raw_amount, col_c, diet_name, warnings)
                    if amount is not None and portion_name:
                        portion_amounts[portion_name] = amount

                amount = _primary_amount(portion_amounts, layout, excel_row)
                unit = (
                    unit_raw.strip()
                    if unit_raw.strip() in VALID_UNITS
                    else DEFAULT_UNIT
                )

                rows.append(
                    ParsedRow(
                        date=current_date,
                        diet_sheet=diet_name,
                        category=current_category,
                        menu_variant=current_variant or "",
                        component_name=col_c,
                        allergens=col_d,
                        amount=amount,
                        unit=unit,
                        notes=notes,
                        portion_amounts=portion_amounts,
                    )
                )
                logger.debug(
                    "      + %s | %s | amount=%s %s",
                    col_c,
                    col_d or "—",
                    amount,
                    unit,
                )
                continue

            # ── separator / empty row — skip silently ─────────────────────────

        return rows


# ── helpers ───────────────────────────────────────────────────────────────────


def _sheet_layout(ws) -> SheetLayout:
    headers = [
        _str(cell)
        for cell in next(ws.iter_rows(min_row=2, max_row=2, values_only=True), ())
    ]
    amount_columns: list[tuple[str, int]] = []
    unit_index = 5
    notes_index: int | None = 6

    for idx, header in enumerate(headers):
        clean = header.strip()
        if clean == "Množstvo":
            amount_columns.append(("", idx))
        elif clean.startswith("Množstvo "):
            amount_columns.append((clean.replace("Množstvo ", "", 1).strip(), idx))
        elif clean == "Jednotka":
            unit_index = idx
        elif clean == "Poznámky":
            notes_index = idx

    if not amount_columns:
        amount_columns = [("", 4)]

    if "Poznámky" not in headers:
        notes_index = None

    return SheetLayout(
        amount_columns=amount_columns,
        unit_index=unit_index,
        notes_index=notes_index,
    )


def _primary_amount(
    portion_amounts: dict[str, Decimal], layout, excel_row
) -> Decimal | None:
    if "Škôlka" in portion_amounts:
        return portion_amounts["Škôlka"]
    if portion_amounts:
        return next(iter(portion_amounts.values()))

    first_portion_name, first_amount_index = layout.amount_columns[0]
    if first_portion_name:
        return None
    raw_amount = (
        excel_row[first_amount_index] if len(excel_row) > first_amount_index else None
    )
    return _parse_amount(raw_amount, "", "", [])


def _cell_val(ws, row: int, col: int):
    """Read a cell value from a (possibly read-only) worksheet."""
    try:
        return ws.cell(row=row, column=col).value
    except Exception:
        # read_only worksheets use iter_rows; fall back to None
        for r in ws.iter_rows(
            min_row=row, max_row=row, min_col=col, max_col=col, values_only=True
        ):
            return r[0]
        return None


def _str(val) -> str:
    if val is None:
        return ""
    return str(val).strip()


def _coerce_int(val) -> Optional[int]:
    if val is None:
        return None
    try:
        return int(val)
    except (ValueError, TypeError):
        return None


def _parse_date_str(raw) -> Optional[datetime.date]:
    if not raw:
        return None
    s = str(raw).strip()
    for fmt in ("%d.%m.%Y", "%Y-%m-%d"):
        try:
            return datetime.datetime.strptime(s, fmt).date()
        except ValueError:
            continue
    return None


def _parse_amount(
    raw,
    component_name: str,
    diet_name: str,
    warnings: List[str],
) -> Optional[Decimal]:
    if raw is None or raw == "":
        return None
    try:
        return Decimal(str(raw))
    except InvalidOperation:
        msg = (
            f"Neplatné množstvo '{raw}' pre komponent '{component_name}' "
            f"v liste '{diet_name}' — hodnota bude ignorovaná."
        )
        warnings.append(msg)
        logger.warning(msg)
        return None


def _fatal(message: str) -> ParseResult:
    """Return a ParseResult carrying a single fatal error and no metadata."""
    result = ParseResult(
        week_year=0,
        week_number=0,
        week_start=datetime.date.min,
        week_end=datetime.date.min,
    )
    result.errors.append(message)
    return result
