# Generated by Django 5.0 on 2026-02-05 14:49

from django.contrib.auth.hashers import make_password
from django.db import migrations


def create_client_user(apps, schema_editor):
    User = apps.get_model("auth", "User")
    if not User.objects.filter(username="client").exists():
        User.objects.create(
            username="client",
            password=make_password("client"),
            email="client@example.com",
            is_staff=False,
            is_superuser=False,
        )


def remove_client_user(apps, schema_editor):
    User = apps.get_model("auth", "User")
    User.objects.filter(username="client").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RunPython(create_client_user, remove_client_user),
    ]
