upstream docker {
    server unix:/var/run/docker.sock;
}

server {
    listen 2375;

    location ~ ^/v1\.[0-9]+/(.*)$ {
        rewrite ^/v1\.[0-9]+/(.*)$ /v1.44/$1 break;
        proxy_pass http://docker;
        proxy_http_version 1.1;
        proxy_set_header Host $http_host;
        proxy_set_header Connection "";
        proxy_read_timeout 600s;
        proxy_send_timeout 600s;
        proxy_buffering off;
    }

    location / {
        proxy_pass http://docker;
        proxy_http_version 1.1;
        proxy_set_header Host $http_host;
        proxy_set_header Connection "";
        proxy_read_timeout 600s;
        proxy_send_timeout 600s;
        proxy_buffering off;
    }
}
